### ISSUE TITLE
feat: extractShebangCommand

### ISSUE THREAD

**Issue by hugojosefson** [hugojosefson/deno-run-simple#6]
Add below function:

```ts
/**
 * Extracts the command to run a script, from its shebang line.
 * @param scriptContents the script source code
 * @returns array of command and parameters
 */
export function extractShebangCommand(scriptContents: string): string[] {
  return scriptContents.split("\n")[0].replace(/^#!/, "").split(" ");
}
```

...with the following edits:

## TODO

- [x] Use `.split("\n", 1)` to not read more than necessary.
- [x] Use [npm:argv-split@2.0.1](https://www.npmjs.com/package/argv-split?activeTab=code) instead of `.split(" ")`.
- [ ] Return some more "Command":y type from this repo?

**Comment by hugojosefson** [comment]
```ts
import argvSplit from "argv-split";

/**
 * Extracts the command to run a script, from its shebang line.
 * @param scriptContents the script source code
 * @returns array of command and parameters
 */
export function extractShebangCommand(scriptContents: string): string[] {
  return argvSplit(scriptContents.split("\n", 1)[0].replace(/^#!/, ""));
}
```
